### ISSUE TITLE
作者有没有群可以探讨呢

### ISSUE THREAD

**Issue by pzdddd** [lack21115/BluedHook#10]
如题

**Comment by lack21115** [comment]
你帮我建一个群咯，建好把群号贴在这里，到时候人多了，我会偷偷混进去。嘻嘻嘻～

**Comment by pzdddd** [comment]
> 你帮我建一个群咯，建好把群号贴在这里，到时候人多了，我会偷偷混进去。嘻嘻嘻～

https://t.me/Chat4Gay

**Comment by lack21115** [comment]
这个是普通的同志群，你的意思不是说要建一个专门讨论 BluedHook 的群吗？

**Comment by lack21115** [comment]
> https://t.me/bluedhook 我来我来🤩

这个可以！

**Comment by lack21115** [comment]
我已入群
