### ISSUE TITLE
极速版7.8.2破解版闪退，打不开app

### ISSUE THREAD

**Issue by HZGHR** [lack21115/BluedHook#4]
安装了提供的极速版7.8.2破解版，闪退，打不开app。
系统：miui12.0.12，安卓10
已核心破解。

**Comment by lack21115** [comment]
破解版只在 红米K30i 5G MIUI12.5.2 上测试成功.
如果你得不行, 可以试试 [SandVXposed](https://github.com/asLody/SandVXposed)

**Comment by HZGHR** [comment]
> 

安装了官方的7.8.2极速版，能够使用防撤回和防闪照。
magsik+lsp
