### ISSUE TITLE
大佬，有在研究本地VIP的悄悄查看么

### ISSUE THREAD

**Issue by miaowyg** [lack21115/BluedHook#6]
如题，我看后续新版本和之前登录的逻辑变化比较大，之前是修改了一个状态值，现在的择不出来了，辛苦大佬考虑考虑这个功能，谢谢了  qaq，觉得还是很实用的一个功能 哈哈哈

**Comment by lack21115** [comment]
我很讨厌已读不回的人, 读了就是读了, 没读就没读, 有啥必要悄悄看?

**Comment by miaowyg** [comment]
技术无罪，你没想过别人为什么对你已读不回么

**Comment by lack21115** [comment]
你说的对！

**Comment by lack21115** [comment]
做好了

**Comment by miaowyg** [comment]
> 做好了

感恩大佬 ，试一下先
